CREATE TABLE IF NOT EXISTS Course(
    courseID UUID PRIMARY KEY NOT NULL,
    teacherID UUID NOT NULL,
    courseName TEXT NOT NULL,
    old BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY(teacherID) REFERENCES Teacher(teacherID)
)